### ISSUE TITLE
annotate in description the need for a checkout repository step

### ISSUE THREAD

**Issue by ryley-lamb** [martinbeentjes/npm-get-version-action#34]
It definitely exposes me as a noob but I was sort of lost on this for a minute and I knew it was me because the current docs are really straight forward.

Maybe it would be good for other noobs like me to add that we need to checkout repository step in our flows. 

```
steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1
```
