### ISSUE TITLE
Problems with path

### ISSUE THREAD

**Issue by juandoplt** [martinbeentjes/npm-get-version-action#9]
I'm not sure if i'm doing something wrong but i keep getting

"cat: can't open './package.json': No such file or directory", although i have one in the root of the project. Could you point me in the right direction ? 

Thanks!

**Comment by jan-tee** [comment]
Should be fixed... when no 'path' argument is supplied, it would default to empty, creating `/package.json` as the path.

**Comment by sypl** [comment]
I'm getting the same thing. Do you need to COPY the package.json in the Dockerfile?

**Comment by connor-mccarthy** [comment]
@sypl @juandoplt Be sure to check out out your repository in your actions file so that GitHub Actions can access it. Otherwise, `npm-get-version-action` will be looking for `package.json` in an empty directory.

See here: https://github.com/actions/checkout

```yaml
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: "Get package version"
        id: package-version
        uses: "martinbeentjes/npm-get-version-action@master"
```

**Comment by martinbeentjes** [comment]
@juandoplt Can you confirm the above fixed your issue?

**Comment by bigfacewo** [comment]
I have the same problem!

**Comment by ngmiduc** [comment]
I have a mono repo, where the pckage.json is in a different folder.
I have set up:
```
defaults:
  run:
    working-directory: ./project/app
```
in my github workflow, but the script can't find the package.json in that folder.

**Comment by KosrenDQ** [comment]
Have the same issue, I used the `actions/checkout@v3`. Maybe there is incompatibility?

```
publish:
    # The type of runner that the job will run on
    runs-on: [self-hosted, default]
    if: github.ref_name == 'master'
    needs: test

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@main
      - name: Build docker file
        run: |
          docker login ${{ secrets.DOCKER_URL }} -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t ${{ secrets.DOCKER_URL }}/app-backend:${{ steps.package-version.outputs.current-version }} .
          docker push ${{ secrets.DOCKER_URL }}/app-backend:${{ steps.package-version.outputs.current-version }}
```
